In [17]:
import numpy as np

a = np.array([[1, 2], [2, 3], [4,5]])
print(a.ndim)
print(a)

2
[[1 2]
 [2 3]
 [4 5]]


In [18]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
b *= 10
b = b.reshape(3, 5)
print(f"b:\n{b}\n")

a = b[1]
print(f"b[1]: {a}\n")

c = b[[0, 2]]
print(f"b[[0, 2]]:\n{c}\n")

b:
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]

b[1]: [ 60  70  80  90 100]

b[[0, 2]]:
[[ 10  20  30  40  50]
 [110 120 130 140 150]]



In [19]:
# Shallow copy
a = np.arange(1, 11)
print(f"a: {a}")

b = a.view()
print(f"b: {b}")

b[0] = 100
print('\nAfter modification in array b:')

print(f"a: {a}")
print(f"b: {b}")

a[1] = 200
print('\nAfter modification in array a:')
print(f"a: {a}")
print(f"b: {b}")

a: [ 1  2  3  4  5  6  7  8  9 10]
b: [ 1  2  3  4  5  6  7  8  9 10]

After modification in array b:
a: [100   2   3   4   5   6   7   8   9  10]
b: [100   2   3   4   5   6   7   8   9  10]

After modification in array a:
a: [100 200   3   4   5   6   7   8   9  10]
b: [100 200   3   4   5   6   7   8   9  10]


In [20]:
c = a[:]
print(f"c: {c}")

c[2] = 300
print('\nAfter modification in array c:')
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")

c: [100 200   3   4   5   6   7   8   9  10]

After modification in array c:
a: [100 200 300   4   5   6   7   8   9  10]
b: [100 200 300   4   5   6   7   8   9  10]
c: [100 200 300   4   5   6   7   8   9  10]


In [21]:
# Deep copy
d = a.copy()
print(f"d: {d}")

d[3] = 400
print('\nAfter modification in array d:')
print(f"a: {a}")
print(f"b: {b}")
print(f"c: {c}")
print(f"d: {d}")

d: [100 200 300   4   5   6   7   8   9  10]

After modification in array d:
a: [100 200 300   4   5   6   7   8   9  10]
b: [100 200 300   4   5   6   7   8   9  10]
c: [100 200 300   4   5   6   7   8   9  10]
d: [100 200 300 400   5   6   7   8   9  10]


In [22]:
# reshape() and resize()

a = np.arange(1, 11)
print(f"a: {a}")
b = a.reshape(2, 5)
print(f"b: \n{b}")

b[0][0] = 10
print('\nAfter modification in array b:')
print(f"a: {a}")
print(f"b: \n{b}\n")

a.resize(5, 2)
print(f"a: {a}")

a: [ 1  2  3  4  5  6  7  8  9 10]
b: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

After modification in array b:
a: [10  2  3  4  5  6  7  8  9 10]
b: 
[[10  2  3  4  5]
 [ 6  7  8  9 10]]

a: [[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [23]:
# flatten() and ravel()
# These methods turn the array to one dimensional array

f = a.flatten()
print(f"flatten f: {f}") # deep copy

f = a.ravel()
print(f"ravel f: {f}") # shallow copy

flatten f: [10  2  3  4  5  6  7  8  9 10]
ravel f: [10  2  3  4  5  6  7  8  9 10]


In [24]:
# T
a = np.array([[1,2,3], [4,5,6]])
a = a.T
print(a)

[[1 4]
 [2 5]
 [3 6]]


In [25]:
# hstack() and vstack()

a = np.arange(1, 10)
b = np.arange(10, 19)

a = a.reshape(3, 3)
b = b.reshape(3, 3)

print(f"a: \n{a}")
print(f"b: \n{b}\n")

res = np.hstack((a, b))
print(f"res: \n{res}\n")

res2 = np.vstack((a, b))
print(f"res2: \n{res2}")

a: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
b: 
[[10 11 12]
 [13 14 15]
 [16 17 18]]

res: 
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]

res2: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [26]:
# Introduction to pandas
import pandas as pd

# Series
grades = pd.Series([56, 80, 70, 90, 100.5])
print(f"grades: \n{grades}\n")

s1 = pd.Series((1, 2, 4, 5, 3))
print(f"s1: \n{s1}\n")

grades: 
0     56.0
1     80.0
2     70.0
3     90.0
4    100.5
dtype: float64

s1: 
0    1
1    2
2    4
3    5
4    3
dtype: int64



In [27]:
d = {'a': 10, 'b': 20, 'c': 30}
s1 = pd.Series(d)
print(f"s1: \n{s1}")

s1: 
a    10
b    20
c    30
dtype: int64


In [28]:
pd.Series(10, [1,2,3])

1    10
2    10
3    10
dtype: int64

In [29]:
a = pd.Series(15, ('a', 'b', 'c'))

In [30]:
a.count()

3

In [31]:
a.min()

15

In [32]:
a.max()

15

In [33]:
a.var()

0.0

In [34]:
a.std()

0.0

In [35]:
pd.Series([50, 60, 70], index = ['a', 'b', 'c'])

a    50
b    60
c    70
dtype: int64

In [36]:
a = pd.Series([10, 20, 30], ['a', 'b', 'c'])
a['b']
a.b

20

In [37]:
s = pd.Series(['ajay', 'vijay', 'sanjay'])


In [54]:
temps = np.array([np.random.randint(60, 101) for _ in range(5)])
temps_series = pd.Series(temps)
temps_series

0     74
1     77
2     74
3    100
4     94
dtype: int64

In [55]:
temps_series.min()

74

In [56]:
temps_series.max()

100

In [57]:
temps_series.mean()

83.8

In [58]:
temps_series.describe()

count      5.000000
mean      83.800000
std       12.296341
min       74.000000
25%       74.000000
50%       77.000000
75%       94.000000
max      100.000000
dtype: float64

In [67]:
# DataFrame
d = {'a': [1, 23, 50, 45], 'b': [12, 25, 14, 8], 'c': [1, 2, 3, 33], 'd': [4, 5, 8, 11]}
d

{'a': [1, 23, 50, 45],
 'b': [12, 25, 14, 8],
 'c': [1, 2, 3, 33],
 'd': [4, 5, 8, 11]}

# a = pd.DataFrame(d)
a